### ISSUE TITLE
Use "abrogation_date" for "published_until"?

### ISSUE THREAD

**Issue by kdeininger** [camptocamp/pyramid_oereb#1336]
Should we map the value of the attribute `abrogation_date` from OEREBlex to the document attribute `published_until`?

**Comment by vvmruder** [comment]
@kdeininger What is the status of this?

**Comment by svamaa** [comment]
As of Mail by @michmuel BL does not need this anymore.
Other cantons neither, according to Usergroup feedback to survey.
