### ISSUE TITLE
Add Python 3.12 support and remove 3.8 support?

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#1851]
Currently, we still support Python 3.8.
However, some dependencies we use require Python 3.9 or later in their latest releases (such as Sphinx https://github.com/openoereb/pyramid_oereb/pull/1838 or c2cwsgiutils https://github.com/openoereb/pyramid_oereb/pull/1827 ) so these can not be updated as long as we offer Python 3.8 compatibility.

At the same time, we can not add Python 3.12 support, because this requires some library updates to versions of the libraries which no longer support Python 3.8. However, we should base our efforts on Python 3.12, because this is the newest Python version which is in Bug-Fix phase.

So we must choose between
* keeping 3.8 support until it is officially EOL and not support Python 3.12
* drop 3.8 support and add Python 3.12 support.

Opinions @vvmruder, @michmuel, @svamaa, @voisardf , others?

**Comment by michmuel** [comment]
We could ask the user group at the next meeting (or before) if someone still uses python 3.8. If that is not the case, or a timely upgrade is feasible for the particular cantons, we could drop the support. Otherwise, extending the support for 3.8 for a few months seems also possible to me.
https://devguide.python.org/versions/

**Comment by svamaa** [comment]
I agree with you @michmuel.
Before we drop the support, we'll have to make sure everyone has enough time to migrate, if still running python 3.8.

**Comment by svamaa** [comment]
As a feedback from the Usergroup, everyone uses Python 3.9 or higher. Thus, we can drop support for 3.8

**Comment by jwkaltz** [comment]
I updated the Python version settings in https://github.com/openoereb/pyramid_oereb/commit/df90f59e964aa8dc36da5e38a6b0911f4548f8b2 

(sorry, I unintentionally pushed it directly to master, I forgot to create a branch. If the CI creates problems, I will revert that)

**Comment by jwkaltz** [comment]
We should do the updates in several steps,
remove Python 3.8,
check separately and with more complete testing that Python 3.12 + required library major upgrades work well.
