### ISSUE TITLE
PDF Extract broken

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#242]
PR https://github.com/camptocamp/pyramid_oereb/pull/236 broke the PDF extract call for me with following error:

`wsgi_1   | Traceback (most recent call last):
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
wsgi_1   |     response = handler(request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
wsgi_1   |     view_name
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
wsgi_1   |     response = view_callable(context, request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
wsgi_1   |     return view(context, request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
wsgi_1   |     return view(context, request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
wsgi_1   |     result = view(context, request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
wsgi_1   |     response = getattr(inst, attr)()
wsgi_1   |   File "/app/pyramid_oereb/views/webservice.py", line 226, in get_extract_by_id
wsgi_1   |     request=self._request
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 146, in render_to_response
wsgi_1   |     result = helper.render_to_response(value, None, request=request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 458, in render_to_response
wsgi_1   |     result = self.render(value, system_values, request=request)
wsgi_1   |   File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 454, in render
wsgi_1   |     result = renderer(value, system_values)
wsgi_1   |   File "/app/pyramid_oereb/contrib/print_proxy/mapfish_print.py", line 155, in __call__
wsgi_1   |     "layout": Config.get('print', {})['template_name'],
wsgi_1   | KeyError: 'template_name'`

I recreated the pyramid_oereb_standard.yml, but still nothing. What am I missing?

Cheers!

**Comment by ger-benjamin** [comment]
Do you have updated your pyramid_oereb.yaml config file since: https://github.com/camptocamp/pyramid_oereb/pull/236 ?

You must have a "template_name" vriable in the "print" section.

**Comment by voisardf** [comment]
Yes, I regenerated the pyramid_oereb_standard.yaml and left the default value:
>    Name of the print tempate to use
>    template_name: A4 portrait

then I did an clean-all and am now having this troubles... :(

**Comment by voisardf** [comment]
ooh, now I get why! 🙈 thanks! 😃

**Comment by ger-benjamin** [comment]
Yes, sorry for that !
