### ISSUE TITLE
Background map on topicpages

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#243]
In the PDF extract there is still the background layer (cadastral map) missing for the restriction topic maps. Normally it is the same that we use for the situation on the title page.

Could you have a look at that or give me instructions? thanks :)

**Comment by voisardf** [comment]
so https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L68 should be the underlaying map to https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L97

**Comment by voisardf** [comment]
Fixed by https://github.com/camptocamp/pyramid_oereb/pull/247
closing

**Comment by sbrunner** [comment]
Not merged yet ...
