### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#251]
I still have an ConnectionError on the master when calling the PDF even with PR https://github.com/camptocamp/pyramid_oereb/pull/249 merged:

```
ConnectionError: HTTPConnectionPool(host='print', port=8080): Max retries exceeded with url: /print/oereb/buildreport.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x08767A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

Do I need to add something in the pyramid_oereb_standard.yml print section to get it working?
```
    # The headers send to the print
    headers:
      Content-Type: application/json; charset=UTF-8
```

**Comment by sbrunner** [comment]
> Do I need to add something in the pyramid_oereb_standard.yml print section to get it working?

Yes :-)

**Comment by voisardf** [comment]
like what?
`host: something` ?

**Comment by voisardf** [comment]
done with print servlet 3.10.2
