### ISSUE TITLE
Complete PDF Extract: attach annexes and removes from TOC

### ISSUE THREAD

**Issue by ebelo** [camptocamp/pyramid_oereb#255]
Todo:

- In the complete extract, follow the annexes links and attach them at the end of the report
- In the TOC, remove the link to the annexes

Jasper doesn't accept PDF files as input. > Use a PDF concatenation App

**Comment by sbrunner** [comment]
We can use pdftk:
https://doc.ubuntu-fr.org/pdftk
https://www.pdflabs.com/tools/pdftk-server/

**Comment by voisardf** [comment]
OK, let's try it :)

**Comment by sbrunner** [comment]
@voisardf From witch attribute did I found the pdf URL?

**Comment by voisardf** [comment]
That should be 'text_at_web' for the standard model

**Comment by sbrunner** [comment]
In LegalProvisions, and it should point to a pdf? it's not the case in the sample data...

**Comment by voisardf** [comment]
the attribute is in the DocumentBase class and inherited

**Comment by voisardf** [comment]
and true, in the sample data the link points to an URL - I think that for the polluted sites of public transportation the act of publication is the legal proof - so a special case :(
