### ISSUE TITLE
FRA PDF translation to double check

### ISSUE THREAD

**Issue by ebelo** [camptocamp/pyramid_oereb#258]
https://github.com/camptocamp/pyramid_oereb/blob/master/print/print-apps/oereb/Report.properties

see if for all strings there is a translation

https://github.com/camptocamp/pyramid_oereb/blob/master/print/print-apps/oereb/Report_fr.properties

**Comment by voisardf** [comment]
Done by PR https://github.com/camptocamp/pyramid_oereb/pull/298

you may cloase the issue if you agree :)

**Comment by vvmruder** [comment]
@ebelo: Can this issue be closed?
