### ISSUE TITLE
LegendSymbol is not rendered into the PDF

### ISSUE THREAD

**Issue by ralphschulerSZ** [camptocamp/pyramid_oereb#277]
Currently we are not able to render a LegendSymbol into the PDF.

https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/4876
Error log:
```
[Mon Oct 09 15:46:13.140035 2017] [wsgi:error] [pid 28283] [remote 46.137.43.181:60052]   File "/srv/apache/schwyz-geoportal/private/schwyz_oereb/.venv/lib/python2.7/site-packages/pyramid_oereb/standard/hook_methods.py", line 112, in get_symbol
[Mon Oct 09 15:46:13.140054 2017] [wsgi:error] [pid 28283] [remote 46.137.43.181:60052]     cast(model.legend_text, Text) == cast(cast(
[Mon Oct 09 15:46:13.140066 2017] [wsgi:error] [pid 28283] [remote 46.137.43.181:60052]   File "/usr/lib/python2.7/base64.py", line 76, in b64decode
[Mon Oct 09 15:46:13.140081 2017] [wsgi:error] [pid 28283] [remote 46.137.43.181:60052]     raise TypeError(msg)
[Mon Oct 09 15:46:13.140101 2017] [wsgi:error] [pid 28283] [remote 46.137.43.181:60052] TypeError: Incorrect padding
```
Is there an error in the code or is something wrong with the data?

It is incomprehensible for me why the database field "legend-text" is base64 decoded?
```python
 try:
        model = DottedNameResolver().resolve('{module_}.{class_}'.format(
            module_=source_params.get('models'),
            class_='LegendEntry'
        ))
        legend_entry = session.query(model).filter(
            model.type_code == type_code,
            cast(model.legend_text, Text) == cast(cast(
                json.loads(base64.b64decode(legend_text).decode('utf-8')), JSONType), Text)
        ).first()
        if legend_entry:
            symbol = getattr(legend_entry, 'symbol', None)
            if symbol:
                response = request.response
                response.status_int = 200
                response.content_type = 'image/*'
                response.body = base64.b64decode(symbol.encode('ascii'))
                return response
        raise HTTPNotFound()
```

**Comment by voisardf** [comment]
I think this is related to https://github.com/camptocamp/pyramid_oereb/issues/270
We are currently trying to solve it. I get the symbols for all the legend entries without special chars, but not the others.

the base64 encoding is necessary for the included text/symbols called by url

[20171011110037_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1375078/20171011110037_extract.pdf)

**Comment by voisardf** [comment]
legend_text comes from the request:
https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/standard/hook_methods.py#L97
therefor the base64

Try the fix from PR https://github.com/camptocamp/pyramid_oereb/pull/280 - does that work for you too?

**Comment by voisardf** [comment]
Should be fixed by PR https://github.com/camptocamp/pyramid_oereb/pull/280.

**Comment by ger-benjamin** [comment]
@ralphschulerSZ @voisardf Can we close this issue ?

**Comment by ralphschulerSZ** [comment]
From my point of view, yes!
