### ISSUE TITLE
Reduced mode contains no ['RealEstate_Highlight']['Image'], right ?

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/pyramid_oereb#278]
So, this code doesn't work in pdf/reduced mode (work in 'full'):  https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L67

@sbrunner  It will be correct to execute it only on "full" ?

**Comment by voisardf** [comment]
👍

**Comment by ger-benjamin** [comment]
:ok_hand:
