### ISSUE TITLE
Remove redundant OEREBlex links

### ISSUE THREAD

**Issue by ralphschulerSZ** [camptocamp/pyramid_oereb#286]
With following example request, we get redundant OEREBlex links:
https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/4876?getspec=true

In my estimation there should be only following items:

- https://oereblex.sz.ch/api/attachments/577 (1 time instead of 3 times)
- https://oereblex.sz.ch/api/attachments/728 (1 time instead of 3 times)
- http://www.lexfind.ch/dtah/125640/2 (1 time instead of 6 times)
- http://www.lexfind.ch/dtah/125641/2 (1 time instead of 6 times)
- http://www.lexfind.ch/dtah/144693/2 (1 time instead of 6 times)
- http://www.lexfind.ch/dtah/147565/2 (1 time instead of 6 times)

According to François this can be done in the component called "mapfish_print_renderer" (or "mapfish_print_proxy"?)

The resulting PDF is attached.
[oereb_extract(18).pdf](https://github.com/camptocamp/pyramid_oereb/files/1394615/oereb_extract.18.pdf)

**Comment by voisardf** [comment]
It's the same problem with other redundant information in the xml/json extract (according to specs). 
We also should regroup and sum restrictions of the same type like "zone de protection 2" and "zone agricole" in the legend - see attached pdf page 3 and 5.

I guess this has to be done in the mapfish_print renderer: https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py

[20171018051356_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1395258/20171018051356_extract.pdf)
