### ISSUE TITLE
Remove symbol display workaround

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#292]
We need the typecode and the content column to get the symbol for some of the federal topics for now (https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/standard/hook_methods.py#L69). But according to the specs and the new model only the typecode should be needed

Once the federal data is fully compliant we have to clean up the 'cast and decode' workaround in the get_symbol() function in https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/standard/hook_methods.py:

```legend_entry = session.query(model).filter(
       cast(model.type_code, Text) == cast(type_code, Text),
       cast(model.legend_text, Text) == json.dumps(json.loads(
       base64.b64decode(legend_text).decode('unicode-escape'))).decode('unicode-escape')).first()
```

**Comment by voisardf** [comment]
using only the typecode I think we can also close this issue? @vvmruder @jwkaltz

**Comment by vvmruder** [comment]
Iam not completely sure if I understood what this is about 😬
