### ISSUE TITLE
HTTPNoContent should not be used for errors

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#304]
In the webservice implementation in the case of a LookupError, we have
"raise HTTPNoContent()":
https://github.com/camptocamp/pyramid_oereb/blob/6354c8f180e29f08927a27fb7d57c81d4f0dd447/pyramid_oereb/views/webservice.py#L205

I think this is wrong, because HTTPNoContent is not an error.
Shouldn't this be "raise HTTPServerError()" instead?

**Comment by kdeininger** [comment]
The LookupError is thrown if a key/index cannot be found in a dictionary/list.
https://docs.python.org/2/library/exceptions.html#exceptions.LookupError

I think this happens, if a real estate with a missing ID is requested. In this case, the specification defines, that a `HTTP 204 No Content` should be returned.

**Comment by jwkaltz** [comment]
OK - but in that case, we should "return HTTPNoContent()", not "raise HTTPNoContent()" ?
Like we already do in the else case further below?

**Comment by kdeininger** [comment]
OK sorry, I think you're right. The case I've mentioned above is handled by the `return HTTPNoContent()`. So maybe it's better to raise a server error here, as you suggested first.

**Comment by jwkaltz** [comment]
@kdeininger thanks for your input, I see that this has disappeared now from the code, we no longer have any raise HTTPNoContent in the project, so I close this issue.
