### ISSUE TITLE
Oereblex, document classification

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/pyramid_oereb#327]
Hi,

Canton Schwyz want some changes for the oereblex documents.
For now, all documents with the "category=related" got to the "Reference" section. They don't want that. They want that all "decree" go to "Rechtsvorschrift" (LegalProvisions) and all "edict" got to "Rechtsgrundlagen" (Reference)
The category will be only used to prioritize the documents ("main" should be upper than "related" in the pdf.)

What should we do ? It is a "standard" wish in terms of Öreblex and pyramid_oereb ?

( @kdeininger do you know something about that ? it's look somehow related to your https://gitlab.com/gf-bl/oereb_server/issues/2 issue )

**Comment by kdeininger** [comment]
It should behave like they expect.

By default, every document of the category `main` gets all the `related` documents attached as references. The doctype specifies which kind of record is created: `decree = LegalProvisionRecord` and `edict = DocumentRecord`.

As far as I understand OEREBlex, there is always **one** main document of the type `decree`. But there might be one or more related decrees.

I've added a config flag, in case you want to treat related decrees also as main document. You can enable it by setting `related_decree_as_main` to `true`. Then the references should only contain documents of the type `edict`.

**Comment by ger-benjamin** [comment]
Oh, okay, thanks. It looks working as they expect with the flag "related_decree_as_main" :-)
