### ISSUE TITLE
New attribute in JSON

### ISSUE THREAD

**Issue by ralphschulerSZ** [camptocamp/pyramid_oereb#337]
We'd like to pass through an existing attribute from OEREBlex into pyramid_oereb. Our goal is to extend the JasperReport with an additional information.

The new attribute should only appear in the PDF-JSON (getspec=true), if possible. But, it doesn't matter if it is in the regular JSON and XML.

Proposal: The new attribute should appear in both "JSON-paths"
**RealEstate_RestrictionOnLandownership/LegalProvisions** and
**RealEstate_RestrictionOnLandownership/Reference** 

Example geolink: https://oereblex.sz.ch/api/geolinks/344.xml

Please also see the attached screenshot as an illustration.

![new_attribute_filetitle](https://user-images.githubusercontent.com/11614900/33650129-fd62d3c0-da60-11e7-9905-e74433ab79ee.png)

**Comment by voisardf** [comment]
OK, I think to get this attribute properly in the PDF without loosing the generalized functionning of the PDF for everybody, we could add an additional band or template with a conditionnal printing - if FileTitle is set, then we print that band and ommit the 'standard band' otherwise not

**Comment by ralphschulerSZ** [comment]
Nice, thank you for this suggestion @voisardf  👍

**Comment by jwkaltz** [comment]
Discussed with @vvmruder , you can do this, but it is customer-specific customization.
