### ISSUE TITLE
unstable JSON output (getspec=true)

### ISSUE THREAD

**Issue by ralphschulerSZ** [camptocamp/pyramid_oereb#341]
In order to test the integrity of the pyramid_server I hacked a little testing script. Sorry, Perl is my "native language" ;-) 

```perl
#!/usr/bin/perl
use strict;
use warnings;
use LWP::UserAgent;
use Data::Dumper;
use Digest::MD5 qw(md5 md5_hex md5_base64);

#my $url = "https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/975?getspec=true";
#my $url = "https://map-t.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/975?getspec=true";
#my $url = "https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001321/1114?getspec=true";
my $url = "https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/1808?getspec=true";

my $ua = LWP::UserAgent->new;
my $req =  HTTP::Request->new( GET => $url);

my $startts = time();
open (STDOUT, ">log_$startts.txt");
print "testing following url: $url\n";

mkdir("./data/$startts");

for (1..50) {
    my $ts = time();
    my $res = $ua->request( $req );
    my $http_status_code = $res->status_line;

    if ($http_status_code eq "200 OK") {
        open(DAT, ">./data/$startts/$ts.$_.json");
        print DAT $res->decoded_content;
        close(DAT);
    } else {
        print STDERR $http_status_code . "\n";
    }    
}

chdir("./data/$startts");

for my $f (<*.json>) {
    my @data;
    print "f: $f.......................................\n";
    open(DAT, $f);
    my @z = <DAT>;
    close(DAT);
    
    for my $r (@z) {
        chomp $r;
        
        next if $r =~ m/CreationDate/;
        next if $r =~ m/ExtractIdentifier/;
        
        push(@data, $r);
    }
    
    print Dumper @data;
    
    my $string = join(";", @data);
    my $md5 = md5_hex($string);
    print STDERR "$f:\t$md5\n";
    print "STRING:\n";
    print "$string\n";    
}
```

As you can see in the log files the server doesn't provide always the same results.

If you compare e.g. these two files you can see the difference: 
\test_json_integrity\data\1512650275\1512650358.5.json
and
\test_json_integrity\data\1512650275\1512650374.6.json

There are other differences as well. Please check the attached log files.

Architecture wise I am not sure if GMF printv3 is involved in the processing if we use "getspec=true". Someone did similar observations?

[test_json_integrity.zip](https://github.com/camptocamp/pyramid_oereb/files/1539143/test_json_integrity.zip)

**Comment by jwkaltz** [comment]
Hi Ralph,
just a comment on part of your question:
There are two JSON to consider, one is the one produced by the oereb server according to specification, for example something like http://localhost:6543/oereb/extract/embeddable/json/CH113928077734
The other one is the one produced for printing purposes in mapfish-print, this is the one you see when you add getspec=true to your report print request. These two JSONs are not the same. Hope that helps.

**Comment by ralphschulerSZ** [comment]
Hi Wolfgang,
thank you for the clarification. What do you think, should I try the same tests with the regular JSON or XML?

**Comment by jwkaltz** [comment]
I guess it depends on the kind of differences that you detect, and whether these are relevant in the sense of the specification. If so, I think it would be interesting to verify the actual extract data first.

**Comment by ralphschulerSZ** [comment]
You can reproduce this manner by starting / stoping Apache and / or  Tomcat. That is to say, I don't expect this on the PRD instance, where more stable conditions prevail.
