### ISSUE TITLE
Missing mapping for RealEstate.type

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#343]
The federal specification defines following output for RealEstate.type:

- 'RealEstate' => e.g. Liegenschaft in BL
- 'Distinct_and_permanent_rights.BuildingRight' => e.g. 'Baurecht' in BL
- 'Distinct_and_permanent_rights.right_to_spring_water' => e.g. 'Quellenrecht' in BL
- 'Distinct_and_permanent_rights.concession' => e.g. 'Konzessionsrecht' in BL
- 'Distinct_and_permanent_rights.other' => e.g. 'weitere' in BL
- 'Mineral_rights' => e.g. 'Bergwerk' in BL

**Comment by vvmruder** [comment]
My solutiuon for this problem would be a configurable mapping in the YAML from federal value to cantonal counter element. Then it is up to the integrator to look what values are in his data.

The above mentioned list is complete.

**Comment by voisardf** [comment]
We could also put this values in the ressource bundle, what do you think? >> Report.properties

**Comment by vvmruder** [comment]
Problem then would be the missing translation in the JSON/XML
