### ISSUE TITLE
Provide mapfish print elements with simple to use method

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#344]
As we have methods for simply create standard YAML file or standard model files, we should also offer a method to provide the oereb print templates for mapfish print to a desired place. For this we need to add all print related stuff to the package-MANIFEST.IN (this is missing in the moment).

In addition we need at least some small documentation which describes how it works.

**Comment by vvmruder** [comment]
In my opinion we have 2 ways how to use this print.

1. Installing it on the same machine
2. Using a already installed print instance elsewhere by extending it with the configuration provided by this package

**Comment by vvmruder** [comment]
What are other suggestions to this?

**Comment by sbrunner** [comment]
Booth looks good, the advantage of the second one is to save some server memory :-)

In this case we recommend to create an new print application in the same print instance.

**Comment by voisardf** [comment]
I agree that we need the possibility to add the pdf print easely to the project
And also recommend the second option - add it to already existing print war(s) - if there are any existing.

**Comment by vvmruder** [comment]
Not a important topic in the moment
