### ISSUE TITLE
Used legend in OtherLegend entries

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/pyramid_oereb#348]
In the pdf report, I've some elements of the legend duplicated in the OtherLegend array.
My legend looks like this (pdf/getSpec output):

````
                "Legend": [
                    {
                        "Area": 44739, 
                        "Geom_Type": "Area", 
                        "Information": "Grundwasserschutzzone S3", 
                        "PartInPercent": 95.4, 
                        "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S3", 
                        "TypeCode": "S3", 
                        "TypeCodelist": "https://models.geo.sz.ch"
                    }, 
                    {
                        "Area": 36043, 
                        "Geom_Type": "Area", 
                        "Information": "Grundwasserschutzzone S2", 
                        "PartInPercent": 76.9, 
                        "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S2", 
                        "TypeCode": "S2", 
                        "TypeCodelist": "https://models.geo.sz.ch"
                    }, 
                    {
                        "Area": 2511, 
                        "Geom_Type": "Area", 
                        "Information": "Grundwasserschutzzone S1", 
                        "PartInPercent": 5.4, 
                        "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S1", 
                        "TypeCode": "S1", 
                        "TypeCodelist": "https://models.geo.sz.ch"
                    }
                ], 
                "OtherLegend": [
                    {
                        "LegendText": "Grundwasserschutzzone S3", 
                        "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S3", 
                        "TypeCode": "S3"
                    }, 
                    {
                        "LegendText": "Grundwasserschutzzone S2", 
                        "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S2", 
                        "TypeCode": "S2"
                    }
                ], 
`````

My question is, is the bug in the print part ?
Perhaps, the JSON is already not correct:

````
                    "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S1",
                    "TypeCode": "S1",
                    ...
                    "Map": {
                        "OtherLegend": [{
                            ...
                            "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S3",
                            "TypeCode": "S3"
                         }, {
                            ....
                            "SymbolRef": "https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/image/symbol/GroundwaterProtectionZones/S2",
                            "TypeCode": "S2"
                        }],
                    },
````

It is normal to get the other "In real estate" objects in the OtherLegend of the PLR ?

Do you get the same behaviors ?

**Comment by vvmruder** [comment]
Hmmm :)

For we are on this in the moment too... But we tested it in our data and we can't confirm that other legend contains elements which are already in the legend.

**Comment by vvmruder** [comment]
can you post a web accessible link to the extract? Than I can have a quick look at it.

**Comment by ger-benjamin** [comment]
I think it's accessible: 
pdf spec: https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/215?getspec
json: https://map-d.geo.sz.ch/bge_oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/215

**Comment by jwkaltz** [comment]
Thanks for your explanation @vvmruder . Regarding your question: my impression is that the pyramid_oereb data preparation should stay close to the data model - so the sorting&merging part to avoid unwanted entries appearing in the print report should thus be done in the print logic. 

But maybe I am missing something, so these are just my first 2 cents.

**Comment by vvmruder** [comment]
Ok. What's about the others? Some more opinions on this?

**Comment by vvmruder** [comment]
About my own opinion: I can live with integrating this sorting logic in pyramid_oereb. For the moment it is only a problem for static extract since we have no "other legend" in dynamic extract. But I can already imagine other services which want use this feature.

And it is not explicitly mentioned in specification nor explicitly forbidden ;)

**Comment by kdeininger** [comment]
I would prefer to stay close to the specification/data model. So every PLR has its own legend symbol and all other visible types are listed in `OtherLegends`. The grouping and sorting of the legend entries should be handled by the client (in this case the print) because there might be different solutions. The static extract needs to display the entries per topic, but maybe another client provides a "per PLR" view which would require a different grouping.

**Comment by voisardf** [comment]
I also agree: Sorting should be done in the print proxy. When an code already exists in the legend it has to be removed from the other legend entries. This is not particularly difficult. We already did it in NE v1:

https://github.com/sitn/crdppf_core/blob/master/crdppf/lib/content.py#L374-L378

**Comment by vvmruder** [comment]
From all these statements I come to the conclusion that the mapfish print proxy should be improved in its sorting and dismissing algorithm.

**Comment by vvmruder** [comment]
Again about the algorithm itself: In the end for the PDF the "per theme" view is important. So the other legend should contain distinct legend entries on the "TypeCode" attribute minus the one which are on the "PLR.TypeCode" in the dedicated theme.

Additional info:
pyramid_oereb already decides what is in the actual WMS view extent. So it is not simply delivering all the legend entries from DB but decides which are visible in actual extent. So this work is done already.

**Comment by ger-benjamin** [comment]
I also agree. It's preferable to stay close to the specification/data model.
(Even if I don't really like the specification. In my own opinion, the mapfish print proxy should not have to do so many transformations to be able to display correctly the data. But that's not the point here)

So I'll implement the supplemental sorting code part in the mapfish print proxy. (I hope I've time to do that today)

**Comment by vvmruder** [comment]
True word :) I dont like it either.

**Comment by vvmruder** [comment]
Thanks for going onto this

**Comment by ger-benjamin** [comment]
Errr. I overestimate myself. I'll ask time to do that the next week.

**Comment by ralphschulerSZ** [comment]
I am not sure if this is off-topic. But at least it should be closely connected with this issue.

Why don't we get a second OtherLegend symbol in this extract?
https://map-d.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/975

![grafik](https://user-images.githubusercontent.com/11614900/34095198-cbd76f40-e3d0-11e7-8ab6-934ec6f5c65e.png)

**Comment by ger-benjamin** [comment]
@ralphschulerSZ Can you open another issue for that ? Or it can it be a lack of data on your side ? (missing information for this brown area ?)
