### ISSUE TITLE
Precision of length, area and percentage

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#350]
The specification states integer values for length, area and percentage of the calulated elements on the real estate. For some reason we developed a "precision" parameter for this in the configuration. This can be removed completely and the "round-logic" can be replaced by a "round + parse to integer logic". I don't remember why we implemented this... :(

**Comment by voisardf** [comment]
For big parcels you could have visible affected surfaces, but a rounded 0% for the restriction. Therefor one decimal for the percentage is a good choice. We have it this way in the pdf and that passed the test :)

**Comment by kdeininger** [comment]
I agree with you, @voisardf. But you should keep in mind that I had to round and parse these values as integer in the XML rendering to get it validated successfully.

**Comment by voisardf** [comment]
so what do we do? Shall we leave it as it is or not?

**Comment by vvmalbre** [comment]
In some checks we found the following wrong behaviour:

Line length should be equal in dynamic and static extract. 

For some real estates this is not the case, see e.g. Binningen 821 

![grafik](https://user-images.githubusercontent.com/3703270/35978044-f45833ae-0ce4-11e8-9aff-e0860b62aeed.png)
![grafik](https://user-images.githubusercontent.com/3703270/35978055-f92f9818-0ce4-11e8-84e9-802650020ad9.png)

see as well:
#379

**Comment by vvmruder** [comment]
solved with #466
