### ISSUE TITLE
Dependency to lxml

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/pyramid_oereb#353]
lxml seems to be defined as a dependency for this project:

https://github.com/camptocamp/pyramid_oereb/blob/master/requirements.txt#L16

Is it used some where ? I was not able to find any trace of that in the project. Moreover, it would be (really) a relief to be able to get rid of that, because it causes some issues when running pyramid oereb on a server with multiple wsgi application, thus not wanting to set `WSGIApplicationGroup %{GLOBAL}` , see:

https://stackoverflow.com/questions/5617599/python-hangs-on-lxml-etree-xmlschematree-with-apache-mod-wsgi

**Comment by kalbermattenm** [comment]
Anyone on this one ??

**Comment by jwkaltz** [comment]
lxml does not seem to be used directly in the pyramid_oereb code, but it is required by some of the libraries that we use, for example geolink_formatter.

**Comment by kalbermattenm** [comment]
OK, thanks a lot. I will discuss this with @voisardf on Wednesday.

**Comment by jwkaltz** [comment]
@kalbermattenm since the question is answered, I am closing this issue.

**Comment by kalbermattenm** [comment]
👍 , thanks @jwkaltz 

ping @voisardf
