### ISSUE TITLE
Inconsistent zoom for topic maps

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#360]
Sometimes the zoom of the map on the topic pages varies and does not display the whole real estate.

see attached pdf
[20180109043732_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1618004/20180109043732_extract.pdf)

**Comment by jwkaltz** [comment]
@voisardf is this issue still relevant, after applying https://github.com/camptocamp/pyramid_oereb/pull/397 (and https://github.com/camptocamp/pyramid_oereb/pull/444)?

**Comment by voisardf** [comment]
As far as I remember, it didn't appear again recently so I'd say it's ok - I'll file a new issue if it should appear again. 👍

**Comment by vvmruder** [comment]
👍
