### ISSUE TITLE
PMRuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by lopo977** [camptocamp/pyramid_oereb#367]
Sometimes we got this error on the last installation we updated yesterday:
PMRuntimeError: dictionary changed size during iteration
we fixed the problem about that dictionary with a deepcopy before iterating on it.

ENV:
debian 8.10
python 2.7.9

there is something strange about site-package pointing to lib/python3.6

=== call stack ==

1/12/2018 3:49:46 PM2018-01-12 14:49:46,596 ERROR [c2cwsgiutils.errors:78][<concurrent.futures.thread.ThreadPoolExecutor object at 0x7f23abf76d30>_5] GET http://dev.sdi.ti.ch:6544/oereb/extract/full/pdf/CH228701020718 returned status code 500: dictionary changed size during iteration
1/12/2018 3:49:46 PMTraceback (most recent call last):
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
1/12/2018 3:49:46 PM    response = handler(request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
1/12/2018 3:49:46 PM    view_name
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
1/12/2018 3:49:46 PM    response = view_callable(context, request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
1/12/2018 3:49:46 PM    return view(context, request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
1/12/2018 3:49:46 PM    return view(context, request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 352, in authdebug_view
1/12/2018 3:49:46 PM    return view(context, request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
1/12/2018 3:49:46 PM    result = view(context, request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
1/12/2018 3:49:46 PM    response = getattr(inst, attr)()
1/12/2018 3:49:46 PM  File "/app/pyramid_oereb/views/webservice.py", line 218, in get_extract_by_id
1/12/2018 3:49:46 PM    request=self._request
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 146, in render_to_response
1/12/2018 3:49:46 PM    result = helper.render_to_response(value, None, request=request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 458, in render_to_response
1/12/2018 3:49:46 PM    result = self.render(value, system_values, request=request)
1/12/2018 3:49:46 PM  File "/usr/local/lib/python3.6/site-packages/pyramid/renderers.py", line 454, in render
1/12/2018 3:49:46 PM    result = renderer(value, system_values)
1/12/2018 3:49:46 PM  File "/app/pyramid_oereb/contrib/print_proxy/mapfish_print.py", line 126, in __call__
1/12/2018 3:49:46 PM    for element in legend_entry.keys():
1/12/2018 3:49:46 PMRuntimeError: dictionary changed size during iteration

=== call stack end==

**Comment by jwkaltz** [comment]
Hi,
You mention an update, do you mean there is a difference in behaviour after your update? What version of pyramid_oereb are you using?

**Comment by lopo977** [comment]
setup(
    name='pyramid_oereb',
    version='1.1.0',
    description='pyramid_oereb, extension for pyramid web frame work to provide '
            'a basic server part for the oereb project',

**Comment by lopo977** [comment]
I am using version 1.1.0 .. last commit on master branch

**Comment by jwkaltz** [comment]
Can you please try with the latest daily build?
1.1.0.dev20180118

**Comment by lopo977** [comment]
I have run a build just now on Ubuntu 16.04 w/o problems.
I plan to try the latest build in a couple of days on the debian 8.5
Thank you.

**Comment by jwkaltz** [comment]
Good - so I close this ticket for now.
