### ISSUE TITLE
No fallback to default translation

### ISSUE THREAD

**Issue by lopo977** [camptocamp/pyramid_oereb#368]
There is no fallback to the default translation when you create an extract in i.e. italian and there is no translation in the DBMS identified by "it"

**Comment by voisardf** [comment]
Hi, yes the italian translation is missing in https://github.com/camptocamp/pyramid_oereb/tree/master/print/print-apps/oereb

You have to create a Report_it.properties file with the corresponding elements to the Report.properties file

**Comment by voisardf** [comment]
I created the file with PR https://github.com/camptocamp/pyramid_oereb/pull/370 but I'm not native italian speaker, so it'll be better if someone of your entity could do the translations or at least check them :)

**Comment by lopo977** [comment]
Thank you. We will review it, with the business.

**Comment by voisardf** [comment]
ok, so the  file is now in the master branch and should serve as default for italian and template for the terms that need translations.

**Comment by lopo977** [comment]
Hi François

here you can find the it translation for the print server.

[Report_it.zip](https://github.com/camptocamp/pyramid_oereb/files/1639512/Report_it.zip)

**Comment by voisardf** [comment]
Thanks. Will be integrated by PR https://github.com/camptocamp/pyramid_oereb/pull/373
