### ISSUE TITLE
Missing development.ini

### ISSUE THREAD

**Issue by lopo977** [camptocamp/pyramid_oereb#369]
Documentation is not up to date.

We cannot debug the application outside the docker container.
We have set up a custom  environment to debug with pserve without the docker container

How do you debug/develop the application outside the docker container?
How do you debug the application inside the container?

Thanks

**Comment by voisardf** [comment]
I did the same thing. I'm debbuging with a local instance using
`.venv\Scripts\pserve --reload development.ini` which should be `.venv\bin\pserve --reload development.ini` on a linux system.

you can use the attached development.txt where you have to replace the DB credentials (username:password) by the real ones you use... 
[development.txt](https://github.com/camptocamp/pyramid_oereb/files/1634672/development.txt)

**Comment by lopo977** [comment]
Thank you! It works!

**Comment by voisardf** [comment]
perfect, thanks for the feedback :)
