### ISSUE TITLE
Mapfish Print: PDF Extract, LandUsePlans, Splitting pages according to subtopics

### ISSUE THREAD

**Issue by sbuettler** [camptocamp/pyramid_oereb#372]
According to the instruction of the Confederation, the LandUsePlans can be splitted into several Subtopics (`sub_theme`). The JasperReport templates have to split (only for the topic LandUsePlans) the Subtopics into several pages. Every Subtopic have to be represented on a separate page and the title of every page must be "topic: sub_theme"

**Comment by jwkaltz** [comment]
Development of this is planned for Ticino in November/December 2018.

**Comment by jwkaltz** [comment]
Solved in #715
