### ISSUE TITLE
Rounding calculated values like area or percentage

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#379]
There is inconsistent part in specification. It is about the precision. For the extracts in JSON/XML format the specification clearly prescribes integer values. For the PDF format it prescribes 1 digit precision float for that values. This is one point to discuss.

In addition rounding values always introduce errors in summarized total amount. So it easily can happen that we have a parcel which points out 100.0 m2 and the elements which are on this parcel are summing up to 100.5 m2.

We need to find a way to do it in the central server part. And in my opinion we need to take these values "as they are delivered" in the rendering part AND in the clients (also in PDF). Otherwise we will get some chaos soon.

**Comment by vvmruder** [comment]
Some suggestions on that?

**Comment by sbrunner** [comment]
What do you mean by saying "as they are delivered"?
In fact I don't understand your last sentence...

For me to have coherent things the rounding should be in the rendering part, not in the core...

**Comment by vvmruder** [comment]
thats true. We should do it in the rendering part. The problem we are facing here is the difference in the specification of the static extract which shows clearly a float with precision 1:
![grafik](https://user-images.githubusercontent.com/3714179/35510462-758a6e50-04f8-11e8-806a-a7390860b395.png)

But the specification for XML DataExtract says that fields which contains this are of type INTEGER...

To bring this to even more confusion everyone knows that javascript (and therefore JSON too) is not supporting pure integer values but the so called number type which is more a float then an integer.

My issue with this is what we wanna do to bring this in a practicable solution

**Comment by vvmruder** [comment]
See #350 too for another branch of discussion

**Comment by jwkaltz** [comment]
@vvmruder do we have a channel where we could validate our interpretation that the % should be float with precision 1 in the static extract?

The screenshot leaves various questions open (number precision respectively its inconsistency with the dataextract; sorting order). It would be good to get some clarification from the specification leaders.

**Comment by vvmruder** [comment]
fixed with #466
