### ISSUE TITLE
Mapfish Print: Legend symbols need frame

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#381]
Specification for static extract says:

![grafik](https://user-images.githubusercontent.com/3714179/35228515-36e64ef6-ff91-11e7-9781-65132c0f2cc7.png)

**Comment by voisardf** [comment]
my bad, indeed. I will improve the templates :)

**Comment by vvmruder** [comment]
super! thanks :)

**Comment by voisardf** [comment]
Done by PR https://github.com/camptocamp/pyramid_oereb/pull/396
