### ISSUE TITLE
XML not valid in XML-Spy

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#385]
XML-Spy delivers "<data:Line>" on validating XML response.

**Comment by vvmdipie** [comment]
Here are two XML-Spy Error Reports:

[XML_Spy_Fehlermeldungen_CH831771598565.docx](https://github.com/camptocamp/pyramid_oereb/files/1695521/XML_Spy_Fehlermeldungen_CH831771598565.docx)
[XML_Spy_Fehlermeldungen_CH887417597077.docx](https://github.com/camptocamp/pyramid_oereb/files/1695523/XML_Spy_Fehlermeldungen_CH887417597077.docx)
