### ISSUE TITLE
XSD links not correct in XML response

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#386]
The XSD urls in the data extract are not correct. They are not pointing to a valid web source.

**Comment by vvmdipie** [comment]
The XSD for Data-Extract 1.10.2016 are here:
https://schemas.geo.admin.ch/V_D/OeREB/Extract(.xsd)
and
https://schemas.geo.admin.ch/V_D/OeREB/ExtractData(.xsd)
