### ISSUE TITLE
Wrong longitude latitude parameter 

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#387]
In the specification there is defined that the order of latitude longitude should be:

xxx?GNSS={longitude},{latitude}

Its the other way round in the moment.

**Comment by voisardf** [comment]
I think I saw that our code takes care of the inversion, but nevertheless it would be better to set the right order by default :)

**Comment by kdeininger** [comment]
I don't think, that the inversion is handled. The order should be fixed.
