### ISSUE TITLE
unpredictable order on OtherLegend and LegalProvision

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#388]
When printing an extract, there is no imposed order of the elements in OtherLegend ("Übrige Legende") and LegalProvision ("Rechtsvorschriften"). Therefore, the order can vary depending on the environment and the data selection implementation. This makes comparisons between / after difficult and also restricts test automation possibilities.

In #359 we introduced an imposed ordering for the "Legend", I guess we should do something similar for OtherLegend and LegalProvision.

**Comment by jwkaltz** [comment]
Should we define an order (e.g. alphabetical according to "Text") for OtherLegend in the extract data already (before any transformation for printing)?
As far as I can tell, we don't have any ordering logic yet, and the specification does not say anything about that.
What do you think @voisardf @vvmruder @kdeininger ?

I guess this concerns not only OtherLegend, but other lists as well.

**Comment by voisardf** [comment]
I'm generally in favor of an ordered display even if it is not mandatory 👍 thanks!

**Comment by vvmruder** [comment]
I introduced the need of a sorting which is *necessary* in issue #380 

@kdeininger can you clarify where this sorting is coming from?

**Comment by jwkaltz** [comment]
@vvmruder @kdeininger for the legend, I introduced a sorting in the mapfish print proxy, because there is actually logic rewriting which entries appear in the legend there, so there is an intermediate python data structure within the print conversion code. Right now, it is sorted by type code. But only for the legend.
AFAICT there is no sorting for any of the other lists, not in the extract preparation and not in the mapfish-print conversion. By the way, @ralphschulerSZ showed me the screenshot of the example in the specification, where the order appears random to me.

**Comment by kdeininger** [comment]
I think, an alphabetical sorting of the elements in `OtherLegend` would be good improvement.

The list of affected public law restrictions should be sorted as described in #380. The sorting by `SubTheme` offers the possibility to group public law restrictions within a certain theme. For example, the topic `LandUsePlans` could be grouped into _basic land use_ and _overlaying land use_. The sorting could ensure, that the _basic land use_ is always shown first in the list, followed by the _overlaying land use_.

**Comment by voisardf** [comment]
👍

**Comment by jwkaltz** [comment]
Thanks for your feedback @kdeininger and @voisardf 
We will try to improve this for schwyz (and of course then do a PR here).

**Comment by jwkaltz** [comment]
Because there have beem several issues about sorting, I would like to summarize the goal and the status of this issue:
- [x] sort OtherLegend alphabetically: this is done, available since today's daily build and tested successfully (in SZ environment)
- [ ] sort LegalProvision alphabetically: not yet done, we will try to improve for schwyz as well (and do a PR for pyramid_oereb).

**Comment by jwkaltz** [comment]
@vvmruder @voisardf @kdeininger the "OtherLegend" is now sorted, but we have just discussed with Schwyz that it is actually not clear whether LegalProvision should be sorted. Schwyz would like to keep the order that their oereblex produces, in cases where the LegalProvisions come from there.

Do you see a need for defining a sort order for LegalProvision in some way? If so, I suggest we open a dedicated issue for that. If there is no such need, we can close the current issue.

**Comment by voisardf** [comment]
As far as I know there is no obligation to sort the LegalProvisions for display (nor the OtherLegend) - The only thing that should be avoided is duplicate entries of documents on the same topic page.

**Comment by jwkaltz** [comment]
Closing, since currently no need for sorting LegalProvisions too
