### ISSUE TITLE
general information is missing in extract

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#391]
It turned out that "general_information" is missing in extract. This should be provided by pyramid_oereb configuration.

**Comment by vvmruder** [comment]
@voisardf I will implement this as configurable text. Can you provide a translation to French later?

**Comment by voisardf** [comment]
yes :)

**Comment by voisardf** [comment]
Done.
Will be completed by https://github.com/camptocamp/pyramid_oereb/pull/394 and PR's https://github.com/camptocamp/pyramid_oereb/pull/396

@jwkaltz : You may close this issue once the PR's merged :)

**Comment by voisardf** [comment]
Romanch is still missing, but the rest is there ;)
