### ISSUE TITLE
Mapfish Print: PDF extract analysis and critics

### ISSUE THREAD

**Issue by sbuettler** [camptocamp/pyramid_oereb#398]
We have analyced our PDF extracts so far, and i would like to share some critics regarding the template of the extract:

1. Position of the **legal base** information is placed under the wrong topic label.

![legal_base information](https://user-images.githubusercontent.com/29145003/35400519-e4f879d8-01ee-11e8-8971-c97dd073a142.jpg)

2. In the table of content are added under attachments the **legal bases** when you call for a full extract, and the title of the topic is not alligned with the page number:

![table of content_legale bases](https://user-images.githubusercontent.com/29145003/35400442-b613f0ca-01ee-11e8-8d48-e965d2b0d42b.jpg)

3. In the table of content are added under attachment the **legal prohibitions**, which aren't PDFs and therfore can't be attached:

![legal_prohibitions](https://user-images.githubusercontent.com/29145003/35400772-98b0320e-01ef-11e8-8f8c-1ae001f7e052.jpg)

4. Page number is wrong, when the table of content gets too long. If the table of content takes 2 pages the page number remains as if the the table of content takes only 1 page.

![page numbering](https://user-images.githubusercontent.com/29145003/35401105-880caa58-01f0-11e8-9fe1-1f83f5ebe900.jpg)

5. Timestamp in the footer is still written in the informatic kind of way :-)

![time stamp](https://user-images.githubusercontent.com/29145003/35401343-207fd760-01f1-11e8-822a-d4d41f4dd64d.jpg)

6. Symbol dimensions not 6x3mm (see instruction of CH). Is it possible to add automatically the black frame of 0.2pt bigness?

![symbol dimensions](https://user-images.githubusercontent.com/29145003/35401561-caedde18-01f1-11e8-8605-32b19a5fa542.jpg)

7. Missing stroke when there are no information in the information table (detail)

![stroke](https://user-images.githubusercontent.com/29145003/35401786-645b694e-01f2-11e8-9882-252b63f6aba2.jpg)

Nevertheless these critics very good work! Thanks!

**Comment by voisardf** [comment]
Hi Sebastian, thanks for the feedback!

I'm aware of some of the issues others I thought fixed... What I'll gone do:

[ ] 1. For this point, in my opinion we have to change the DB structure a little and ad a table legal_bases the same as we have it for legal_provisions 
@vvmruder @sbrunner @jwkaltz Do you agree? Or do you see an other way to distinguish easely between legal bases and other reference document?
[ ] 2. OK, I thought that was improved - I will check and fix this if needed
[ ] 3. I give it a look, but as the FULL PDF is no longer a requirement, it's not first point on the list ;)
[ ] 4. Hmm, that's bad. I'll have a look at the condition. But like point 3 it's an issue of the FULL pdf
[ ] 5. I thought it has been done - I'll check and improve if not done.
[ ] 6. The border has been added in PR https://github.com/camptocamp/pyramid_oereb/pull/396 and it seemed to me that we defined the icons as 6x3mm (or at least the next possible value in px). I'll check and fix if needed.
[ ] 7. OK, not done. I've seen it but not implemented. I will fix it :)

**Comment by sbuettler** [comment]
Thanks for the answer:

Proposal: wouldn't it work also, if we define a new document type for the table `document_base`? Like: legale_bases

![document_base](https://user-images.githubusercontent.com/29145003/35441588-5f37af7e-02a4-11e8-9e23-6197a28f4b52.PNG)

**Comment by voisardf** [comment]
yes that would work, it's how we implemented it in NE for the v1.
But for the pyramid_oereb it would proabably be easier to use a second table. Any opinions on that? @sbrunner  @vvmruder @jwkaltz @kdeininger

**Comment by kdeininger** [comment]
You're right François. We need an additional table which inherits from `document`, like `legal_provision` does.

The current version of the specification adds a new document type attribute in the extracts:
https://github.com/camptocamp/pyramid_oereb/blob/master/tests/resources/schema/draft/extractdata.json#L245-L247

There are three document types defined: `legal_provision`, `law` and `hint`. They correspond to the three sections in the PDF. But I don't know how the decision between `law` and `hint` should be done using the transfer structure.

![image](https://user-images.githubusercontent.com/5467596/35506927-555b6448-04eb-11e8-993d-d448b2696f27.png)

Anyway, we have two options:

1. Add the document type attribute but keep using the old specification version **(this might cause the validation to fail!)**
2. Force the implementation of the current specification (has to be done anyway)

**Comment by vvmruder** [comment]
@sbuettler About the Icon size: This only depends on what icons you provide in your data. They are stored in the legend entry table for each legend entry under the attribute "symbol". To have them there you need to create them. Therefore a tool in pyramid_oereb is existing which we call the "pyconizer" you can access it via the console through the programm call: `create_legend_entries`

For further details see `create_legend_entries -h`

Its a little bit a hack to get it workting. Don't hesitate to contact me directly for more information.

**Comment by jwkaltz** [comment]
@sbuettler after discussing this with Clemens, we believe most issues within this issue are no longer present.
Can you please check again in your current installation which issues are still open, and create a separate issue for each such issue?
