### ISSUE TITLE
No dividers per thousand steps in numeric fields

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#405]
For the calculated Area and other fields we have a number format like this: 1.000 m2
The Specification for static extract says this:
![grafik](https://user-images.githubusercontent.com/3714179/35511212-607d1910-04fb-11e8-8e3d-0d1c92367839.png)
So "1.000" should be "1000" in the PDF

**Comment by sbrunner** [comment]
Do we relay make it less readable?

**Comment by vvmruder** [comment]
@sbrunner I know... 

But the federal inspectors who are checking this are really serious about it. Because the "." is the decimal sign.

If you wanna hear my personal favorit: It should be like "1'000'000". But my personal idea is not counting here :(

**Comment by sbrunner** [comment]
I agree with them for the dot, Is it OK for them to put a ' or a space as a separator or do they explicitly want nothing?

**Comment by vvmruder** [comment]
explicit nothing

**Comment by sbrunner** [comment]
OK :-(

**Comment by kdeininger** [comment]
Fixed with #466
