### ISSUE TITLE
Format of municipality on first page is not conform to specification

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#408]
Actual situation is like:
![grafik](https://user-images.githubusercontent.com/3714179/35511892-068ee11a-04fe-11e8-80f0-d524e59515af.png)

Specification says:
![grafik](https://user-images.githubusercontent.com/3714179/35511943-3dc5decc-04fe-11e8-8036-6403aba69497.png)

**Comment by sbrunner** [comment]
I don't understand why you have an issue, when I see that
https://github.com/camptocamp/pyramid_oereb/blob/master/print/print-apps/oereb/mainpage.jrxml?utf8=%E2%9C%93#L233
you shouldn't have extra space, except if the RealEstate_Municipality ends with spaces....

**Comment by kdeininger** [comment]
Yes, it's a problem with the municipality data :wink:
