### ISSUE TITLE
Date format in footer on every page is wrong

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#411]
In the moment the PDF looks like:
![grafik](https://user-images.githubusercontent.com/3714179/35512200-266b1f5c-04ff-11e8-9f03-05e12c874003.png)

Specification says:
![grafik](https://user-images.githubusercontent.com/3714179/35512215-3261f434-04ff-11e8-8ec8-2289088f986c.png)

**Comment by voisardf** [comment]
will be done by my PR https://github.com/camptocamp/pyramid_oereb/pull/400

**Comment by voisardf** [comment]
I know you are under pressure guys, but are you sure that you are working on the latest templates? It seems to me that some of the design issues should not be there anymore... 🤔
