### ISSUE TITLE
TOC does not contain "Anhänge" if they are not existent

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#412]
I'am not sure what to decide here. Mostly the PDF extract shows all elements even if they do not have data. Often with a "-" then.

We have this also with the "Anhänge" when we do not have any in our extract:
![grafik](https://user-images.githubusercontent.com/3714179/35512346-c34ae154-04ff-11e8-84cf-565add668403.png)

Questio here is now: Should we show this "Anhänge" when there are none? In my opinion we can discard this. Especially when we will skip the complete pdf in the future anyway.

What do you think?

**Comment by voisardf** [comment]
As I remember it, it's said somewhere in the specs, that this element should not appear unless there are appendices.
So I suggest to close this issue. :)

**Comment by vvmruder** [comment]
Ok so we will keep this and close this issue?

**Comment by voisardf** [comment]
for me yes, we can close this issue - if a reduced PDF is called, 'Anhänge' should not appear. 
If the full PDF should be called one day, the label has to appear

**Comment by vvmruder** [comment]
Ok for me. Thanks for attention :)
