### ISSUE TITLE
Font type and size, and spacing seems not consistent

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#413]
Over all look is not really conform to the specification.

The spacing for TOC for instance.

**Comment by voisardf** [comment]
Did you already start working on this, because some elements will be addressed in my next PR https://github.com/camptocamp/pyramid_oereb/pull/433

**Comment by vvmruder** [comment]
He was looking on this. But it seems to be a little bit complex. But what we found out is, that is is possible to set *.5 as font size in jrxml templates manually. And this worked as far as we could see?!

**Comment by voisardf** [comment]
yeah, you can set it manually, but I get issues with linespacing for multi-line text: e.g. If you have 3 lines for a polluted site legend entry, it would only display 2... :(

**Comment by vvmruder** [comment]
@voisardf What is going on here? Is this solved in your opinion?

**Comment by jwkaltz** [comment]
Deprecated -> new issue https://github.com/camptocamp/pyramid_oereb/issues/545
