### ISSUE TITLE
Find a system to extend default model

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/pyramid_oereb#447]
Currently we must copy-past and lot of file only to add a simple column in the database (for instance the "lexlink", also sometimes known as "geolink", for the OEREBlex system). That's hard to maintain. We must find a better system to be able to extent the default pyramid_oereb model.

One idea from here: https://github.com/camptocamp/pyramid_oereb/pull/435#issuecomment-362553364
> ...we can provide a mako file which is creating models files via console script. More or less the same way we went with the standard database models.

**Comment by jwkaltz** [comment]
This has been done in https://github.com/camptocamp/pyramid_oereb/pull/503,
but should still be documented in https://camptocamp.github.io/pyramid_oereb/doc/configuration.html#add-additional-topics

**Comment by vvmruder** [comment]
Regarding to discussion with @jwkaltz I give a :+1: on this topic. We can add standard-oereblex models to the contrib section of the project to reduce redundant code.

**Comment by jwkaltz** [comment]
One simple idea would to be provide a set of cantonal themes that everybody uses in an "oereblex" variant,  within pyramid_oereb.
This would be some code duplication within pyramid_oereb itself, but would reduce code duplication across user projects.

**Comment by pfirpfel** [comment]
solved by #767:
- Added two make tasks:
  - create-default-models
  - create-oereblex-models
- Adding cantonal oereblex models to `pyramid_oereb/contrib/models/oereblex/`
