### ISSUE TITLE
Call on xml extract throws error if translations are missing

### ISSUE THREAD

**Issue by marionb** [camptocamp/pyramid_oereb#455]
If translations are missing calling the xml fails here:

https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/templates/xml/multilingual_text.xml#L8

The error should be handled and the user should probably get informed in a log or something.

**Comment by vvmruder** [comment]
I cant confirm this. If I try to get en extract with url parameter `lang=sw` (for Swahili language which is not implemented for sure). I get correct error:
https://geoview.bl.ch/main/oereb/extract/reduced/xml/geometry/CH630779395731?_dc=1536056080088&LANG=sw

If I try to use some of possible languages like `fr` which is implemented but has no data in our database then I get the extract in `de` (the configured standard language) for the elements which are not federal (they have fr in their data:
https://geoview.bl.ch/main/oereb/extract/reduced/xml/geometry/CH630779395731?_dc=1536056080088&LANG=fr
