### ISSUE TITLE
About all the rounding of values

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#458]
I want to summarize what my idea/opinion is about what we have in the moment: Its an chaos...

After I had a detailed look on what goes on in the different places of the application I came to the point that we need to fix this centrally.

What am I talking about?
The calculated values in the extract for every PLR. We calculate the values inside the application. We rely on the configured settings for precision. We pass the values through the renderers to produce the DataExtract in whether JSON or XML. Later in clients like PDF/dynamic client we sum up the different values and ROUND again. This shouldn't be. We need to clean this up. The clients shouldnt change anything on the values. Only summarize them is ok.
Otherwise Iam afraid, we wont get any straight logic in this system :(

I reference on the issues: #379, #350 an PR #445

@voisardf @kdeininger @jwkaltz @sbrunner @ger-benjamin 
What are the other opinions?

- [x] fix int parsing in https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L354
- [x] Pass land registry area as integer
- [x] Add a comment that this is silly but will be fixed on new extract schema: https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/templates/xml/public_law_restriction.xml#L39

**Comment by vvmruder** [comment]
Ok nobody seems to be interested here to solve this ;)

So I will start with some (in my mind) silly examples:

This line uses `int(<float>)` to parse a calculated float to an integer:
https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L354

REALLY BAD: int(99.9) parses to 99 😲

**Comment by kdeininger** [comment]
The land registry area is passed as string to Mapfish Print:
https://github.com/camptocamp/pyramid_oereb/blob/d7b6dacd605b9979afc22950c4ebfbc217e4a9f8/print/print-apps/oereb/config.yaml#L68
https://github.com/camptocamp/pyramid_oereb/blob/d7b6dacd605b9979afc22950c4ebfbc217e4a9f8/print/print-apps/oereb/mainpage.jrxml#L33

This should be changed to integer.

**Comment by ger-benjamin** [comment]
That probably simplistic, but from my point of view,
 1. Only the final renderer (JSON / XML) must round a value. Even if that cost a little bit more along the process.
 1. These round functions should be the same in both cases (like in the __init__.py of the renderer).
 1. The pdf should not round any value. It should receive the same values as in the JSON. With sumed values, I'not sure if it should round them, or if the sumed values should be also in the json...

**Comment by sbrunner** [comment]
I agree with @ger-benjamin but with this we cont have deferent rendering in the json as in the pdf, If we want deferent precession the rounding should be in the jasper template and be optional in the json rendering

**Comment by vvmruder** [comment]
we do not want different rendering. This is exactly what we do not explicitly not, I mean really not want...

**Comment by vvmruder** [comment]
The numeric results should be exactly the same in PDF, JSON, (XML => next version), dynamic client

**Comment by ger-benjamin** [comment]
> We need to do a int(round(<float>)) here as it is done in xml renderer in the moment:
https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/templates/xml/public_law_restriction.xml#L39

Can't we round it also in the json ? (to be coherent between xml and json ?)

**Comment by vvmruder** [comment]
Ok now we come to the funny thing: The common federal specification about the data types (not explicitly XML) says:
![grafik](https://user-images.githubusercontent.com/3714179/36259014-19f8f0b2-125d-11e8-815c-92ea68953810.png)

This does not make any sense. I know, I know. Since we are not sticked to any validation for the JSON format because JSON cant have simple integer but number we (@kdeininger and me) decided to do the logic and coherent stuff in all application => having area as integer and partinpercent as float with one precision. This will be done in central point. Only exception will be the mentioned line in XML-and only until we are allowed to put this to float too.

**Comment by vvmruder** [comment]
In the end only sum up values is allowed for the clients (dynamic/pdf).

**Comment by kdeininger** [comment]
My preferred solution would be:

1. Round and render area and length values as integer (should be done in processor, no special handling in renderers).
2. Round and render "PartInPercent" as decimal/float with one decimal place.
3. Add temporary workaround for XML rendering by rendering "PartInPercent" as integer until we support the new XML schema.

**Comment by kdeininger** [comment]
The currently used schema (20160830):
https://github.com/camptocamp/pyramid_oereb/blob/21b2670fdb99c10d396805ce3ec70cc6b90f30ac/tests/resources/schema/20160830/ExtractData.xsd#L363-L370
The new schema (20170825):
https://github.com/camptocamp/pyramid_oereb/blob/21b2670fdb99c10d396805ce3ec70cc6b90f30ac/tests/resources/schema/20170825/ExtractData.xsd#L413-L420

**Comment by voisardf** [comment]
I completely agree that rounding should be done in the last step only. 
If the federal specs say otherwise, we have to rely this back to the responsible persons, so that we get a decision how to handle it for now and hopefully have a fixed spec later on.

@vvmruder : I'm sorry, but I do not get the 'funny thing'? 🤔 
For me that Interlis definition looks ok - Area is indicated as integer - which does not mean that it can't be changed to decimal/float during calculation and rounded to integer again when displaying while the percentage obviously has to be decimal to make any sense.

So for me in the processor all math should be done in decimal, and rounding functionnality implemented in the rendering or in a global functionality able to be accessed by all renderers to have a consistent calculation and just one place where it's done (like multilingual text :) ).
Does that make sense to you? Feasible? Complicated?

my 2 cents

**Comment by kdeininger** [comment]
Solved with #466
