### ISSUE TITLE
warning when running tests

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#461]
When running the automated tests, the following warning appears:

`tests/sources/test_document_oereblex.py::test_read
  /home/wkaltz/src/pyramid_oereb/pyramid_oereb/lib/records/documents.py:126: UserWarning: Type of "abbreviation" should be "dict"
    warnings.warn('Type of "abbreviation" should be "dict"')
`

The test should be improved here.

**Comment by jwkaltz** [comment]
no such warning appears when running test suite as per #729 .
So issue can be closed after that PR is merged, ping @pfirpfel

**Comment by pfirpfel** [comment]
fixed with #729
