### ISSUE TITLE
NameError: name 'unicode' is not defined - Python3

### ISSUE THREAD

**Issue by lopo977** [camptocamp/pyramid_oereb#472]
https://github.com/camptocamp/pyramid_oereb/blob/5bfb787e54394436c37401e2ff1c174e5c2c9e0e/pyramid_oereb/lib/renderer/__init__.py#L160

is this method still working with python3

**Comment by vvmruder** [comment]
Isn't it fixed in master already?

**Comment by vvmruder** [comment]
And to answer the question: It is not working in Python > 3.4

**Comment by jwkaltz** [comment]
Has been fixed
