### ISSUE TITLE
too many OtherLegend entries

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#473]
Schwyz reported that some of their extracts have too many OtherLegend entries.

The most recent version at Schwyz uses pyramid_oereb version 1.1.0.dev20180214, it can be seen here: https://map-d.geo.sz.ch/wkaltz_oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/4009
This has 5 entries in OtherLegend of the Nutzungsplan kommunal, but 2 of them are wrong: notably, "Gefahrenhinweis", because the parcel is quite far away from areas with Gefahrenhinweis.

I think this is due to a bug in pyramid_oereb. I wonder if any other users experience this?

Note that this was not the case in the past; I was able to pin down the origin to https://github.com/camptocamp/pyramid_oereb/pull/390. 

Here is a version running the commit just prior to this PR: https://map-d.geo.sz.ch/old_wkaltz_oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/4009

Running the version just after this PR, https://map-d.geo.sz.ch/middle_wkaltz_oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/4009
there are 6 entries, so 3 elements including "Gefahrenhinweis" which should not be there (so even one more element than in the most recent version that should not be there).

**Comment by voisardf** [comment]
Hi, unfortunately I can confirm that there are too many OtherLegend entries now in the latest master.

**Comment by vvmruder** [comment]
@jwkaltz & @voisardf : can you confirm that you encounter this issue on topics defined as collection geometries (for instance land use plans) only?

**Comment by vvmruder** [comment]
additional question: In the moment on the legend entries the same threshold mechanism is used like for the results. This is leading to the following behaviour:
![grafik](https://user-images.githubusercontent.com/3714179/37292027-4ad3f6fc-2610-11e8-8be8-658298ad71f4.png)

The small element is visible in map but not in other legend. What should we do here? Any suggestions are welcome.

**Comment by vvmruder** [comment]
Just for let you know: If you can confirm the GeometryCollection thing, I think I tracked the error down.

**Comment by vvmruder** [comment]
@jwkaltz : can you try out the solution in #481 and check if this solves the problem?

**Comment by ralphschulerSZ** [comment]
@vvmruder : I can confirm the GeometryCollection assumption. At least I didn't saw this behavior on non-GeometryCollection themes.

**Comment by jwkaltz** [comment]
@vvmruder I applied the changes proposed in #481 and re-tested with my test-case:
https://map-d.geo.sz.ch/wkaltz_oereb/wsgi/oereb/extract/reduced/pdf/SZ0200001372/4009
Now, "Gefahrenhinweis", "Gefahrenzone mit erheblicher Gefährdung" and "Übriges Gemeindegebiet" no longer appear in the "Übrige Legend". The rest of the extract is unchanged.

As far as I understand, this is the correct situation - @ralphschulerSZ can you please look at this and confirm? So far, changes have only been applied manually to https://map-d.geo.sz.ch/wkaltz_oereb, but you can use that instance to test.
