### ISSUE TITLE
New specification defines standard abbreviations

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/pyramid_oereb#549]
The new abbreviations are:

AltIV: Verordnung über die Sanierung von belasteten Standorten (Altlasten-Verordnung) (SR 814.680)
BFS-Nr.: Amtliche Gemeindenummer
EBG: Eisenbahngesetz (SR 742.101)
E-GRID: Eidgenössische Grundstücksidentifikation
GeoIG: Bundesgesetz über Geoinformation (Geoinformationsgesetz) (SR 510.62)
GeoIV: Verordnung über Geoinformation (Geoinformationsverordnung) (SR 510.620)
GSchG: Bundesgesetz über den Schutz der Gewässer (Gewässerschutzgesetz) (SR 814.20)
GSchV: Gewässerschutzverordnung (SR 814.201)
KbS: Kataster der belasteten Standorte
LFG: Bundesgesetz über die Luftfahrt (Luftfahrtgesetz) (SR 748.0)
LSV: Lärmschutz-Verordnung (SR 814.41)
NSG: Bundesgesetz über die Nationalstrassen (SR 725.11)
ÖREB: Öffentlich-rechtliche Eigentumsbeschränkung
ÖREB-Kataster: Kataster der öffentlich-rechtlichen Eigentumsbeschränkungen
ÖREBKV: Verordnung über den Kataster der öffentlich-rechtlichen Eigentumsbeschränkungen (SR 510.622.4)
RPG: Bundesgesetz über die Raumplanung (Raumplanungsgesetz) (SR 700)
RPV: Raumplanungsverordnung (SR 700.1)
USG: Bundesgesetz über den Umweltschutz (Umweltschutzgesetz) (SR 814.01)
VIL: Verordnung über die Infrastruktur der Luftfahrt (SR 748.131.1)
WaG: Bundesgesetz über den Wald (Waldgesetz) (SR 921.0)

![grafik](https://user-images.githubusercontent.com/3714179/42094943-83a8db7c-7bb1-11e8-8965-f03804b5781e.png)

![grafik](https://user-images.githubusercontent.com/3714179/42094961-9049f622-7bb1-11e8-8546-e6b787e98c87.png)

New specification:
[Weisung-statischer-Auszug-de.pdf](https://github.com/camptocamp/pyramid_oereb/files/2149548/Weisung-statischer-Auszug-de.pdf)

We should add these abbreviations to the Glossar table in the standard database application schema.

**Comment by marionb** [comment]
**For Info:** 

I'm using the following documents for translations:

- https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/publication/instruction.download/cadastre-internet/de/documents/oereb-weisungen/Weisung-statischer-Auszug-de.pdf
- https://www.cadastre.ch/content/cadastre-internet/it/manual-oereb/publication/instruction.download/cadastre-internet/it/documents/oereb-weisungen/Weisung-statischer-Auszug-it.pdf
- https://www.cadastre.ch/content/cadastre-internet/fr/manual-oereb/publication/instruction.download/cadastre-internet/fr/documents/oereb-weisungen/Weisung-statischer-Auszug-fr.pdf

It appears there is no RM translation the following link does not work. Until other notice I will leave the translation bank as it was done in other cases
- https://www.cadastre.ch/content/cadastre-internet/rm/manual-oereb/publication/instruction.download/cadastre-internet/rm/documents/oereb-weisungen/Weisung-statischer-Auszug-rm.pdf
