### ISSUE TITLE
pyramid 1.2.2 doesn't support new schema

### ISSUE THREAD

**Issue by ralphschulerSZ** [camptocamp/pyramid_oereb#616]
I've installed the newest daily build from https://pypi.org/project/pyramid_oereb/1.2.2.dev20180826/ on my personal instance.

As it seems the XML-extract does not support the new schema.
https://map-d.geo.sz.ch/rschuler_oereb/wsgi/oereb/extract/reduced/xml/SZ0200001372/1808

According to the requirements document https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/publication/instruction.download/cadastre-internet/de/documents/oereb-weisungen/OEREB-XML-Aufruf_de.pdf , there should be following string in the extract:
```xml
xmlns="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract.xsd"
```

For now, there is still the old one:
```xml
xmlns="https://schemas.geo.admin.ch/V_D/OeREB/Extract.xsd"
```

**Comment by kdeininger** [comment]
I think there must be something wrong with the installation.

That's the current version of the XML template:
https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/templates/xml/extract.xml

The namespaces look fine to me. They have been fixed with #586 (02.08.2018). Are you sure, you've used the latest daily build?

**Comment by vvmruder** [comment]
I also can't confirm. I quickly installed the current nightly build. You can see result here:

[CH167007395868.xml.txt](https://github.com/camptocamp/pyramid_oereb/files/2324527/CH167007395868.xml.txt)

As far as I checked this. The result looks good.

**Comment by ralphschulerSZ** [comment]
Sorry, my bad. I must have confused something. I will test it again an let you know. Thank you.

**Comment by jwkaltz** [comment]
So I close this ticket, the namespace is correct (in 1.2.2 daily builds).
