### ISSUE TITLE
Content test-db

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#621]
How comes that I have 12-create.sql and 13-fill.sql in my local test-db folder and they are not existing under
https://github.com/camptocamp/pyramid_oereb/tree/master/test-db anymore?
Did I miss something?

**Comment by jwkaltz** [comment]
These files are generated automatically, during a "make serve", based on the model code.

**Comment by voisardf** [comment]
OK, thanks - sounds quite logic :)
