### ISSUE TITLE
Print_proxy Python 3 incompatibility blocks pdf creation

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#695]
In the mapfish print proxy is an iteration over the keys of the legend_entry element deleting some elements which is not compatible with Python 3 (the method returns the iterator instead of a list).

https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L234

the keys should be fetched into a list:
                for element in list(legend_entry.keys()):

I'll push a fix next week

**Comment by jwkaltz** [comment]
Closed by #696 , thanks @voisardf

**Comment by svareg** [comment]
Can this correction be applied to version 1.2.3 as well ?

**Comment by jwkaltz** [comment]
@svareg no (1.2.3 is already released), but you can use a current daily build, see https://pypi.org/project/pyramid_oereb/#history
If you do this, you will need to make some small changes, as described here: https://camptocamp.github.io/pyramid_oereb/doc/changes.html#version-1-nextversion
