### ISSUE TITLE
ContaminatedCivilAviationSites: which geometry type?

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#712]
In the current standard project configuration, ContaminatedCivilAviationSites has geometry type POLYGON:
https://github.com/camptocamp/pyramid_oereb/blob/bb605e65219dd95e9b21d534b1dd8f91f136fc3a/pyramid_oereb/standard/pyramid_oereb.yml.mako#L645

However, as tested with @thomasmarti, federal data for this theme seems to come as geometrycollection, not polygon.

Should our standard configuration (and model) be changed?

**Comment by voisardf** [comment]
Yes, we should change the standard type. Thanks!

**Comment by jwkaltz** [comment]
Fixed in #713
