### ISSUE TITLE
BBOX incorrectly calculated

### ISSUE THREAD

**Issue by peterschaer** [camptocamp/pyramid_oereb#717]
There seems to be a bug in calculating the bbox. If a real_estate geometry is wider than tall, then its bbox is calculated incorrectly. If a real_estate feature is taller than wide, everything is ok. This bug has several effects:

- all the wms urls in json/xml are wrong
- too many legend items in other legend

the problem does not occur in the pdf, because in the printproxy the bbox is eliminiated and the zoomtofeatures-option of mapfish-print is used.

I have an example from our data:

[20181204043933_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/2644694/20181204043933_extract.pdf)

on page 3 there are 12 other legend items, only two of them are visible in the map

in the json of the same parcel we have the following wms links:

[PLR-WMS](https://oerebservice.apps.be.ch/cgi-bin/mapserv.fcgi?LAYERS=geodb.nupla_gngruzo&map=oereb_de&CRS=EPSG%3A2056&FORMAT=image%2Fpng&REQUEST=GetMap&SRS=EPSG%3A2056&HEIGHT=280&WIDTH=493&VERSION=1.3.0&BBOX=2587248.09881%2C1219306.5826%2C2587876.87419%2C1220413.6764&EXCEPTIONS=xml&TRANSPARENT=TRUE&BGCOLOR=0xFFFFFF)
and 
[Parcel-WMS](https://oerebservice.apps.be.ch/cgi-bin/mapserv.fcgi?LAYERS=geodb.mopube_bbf%2Cgeodb.mopube_bbprjf%2Cgeodb.mopube_eof%2Cgeodb.mopube_rlf%2Cgeodb.mopube_liprjf%2Cgeodb.mopube_lisrprjf%2Cgeodb.mopube_lif%2Cgeodb.mopube_lisrf%2Cgeodb.mopube_hgf%2Cgeodb.mopube_hohk%2Cgeodb.mopube_rll%2Cgeodb.mopube_eol%2Cgeodb.mopube_eop%2Cgeodb.mopube_hgprjf%2Cgeodb.mopube_hgabschl%2Cgeodb.mopube_hoehep%2Cgeodb.mopube_hgp%2Cgeodb.mopube_ligp%2Cgeodb.mopube_fixp%2Cgeodb.mopube_rlltxt%2Cgeodb.mopube_rlftxt%2Cgeodb.mopube_bbprjtxt%2Cgeodb.mopube_bbtxt%2Cgeodb.mopube_gastrnat%2Cgeodb.mopube_nonamtxt%2Cgeodb.mopube_eoftxt%2Cgeodb.mopube_eoltxt%2Cgeodb.mopube_eoptxt%2Cgeodb.mopube_gaeintxt%2Cgeodb.mopube_lisrprjt%2Cgeodb.mopube_liprjtxt%2Cgeodb.mopube_lisrtxt%2Cgeodb.mopube_litxt&map=oerebav_de&SERVICE=WMS&CRS=EPSG%3A2056&FORMAT=image%2Fpng&REQUEST=GetMap&SRS=EPSG%3A2056&HEIGHT=280&STYLES=%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C%2C&WIDTH=493&VERSION=1.3.0&BBOX=2587248.09881%2C1219306.5826%2C2587876.87419%2C1220413.6764&EXCEPTIONS=XML&TRANSPARENT=TRUE&BGCOLOR=0xFEFFFF)

Both images are somewhat distorted.

I found a similar example in Basel-Land:

[PDF](https://geoview.bl.ch/main/oereb/extract/reduced/pdf/CH815970177712)
[JSON](https://geoview.bl.ch/main/oereb/extract/reduced/json/geometry/CH815970177712)

In the json e.g. the following wms url is contained:

[Parcel-WMS](https://geowms.bl.ch/?STYLES=default&LAYERS=grundbuchplan_gebaeude_nicht_gefuellt_group&SERVICE=WMS&FORMAT=image%2Fpng&REQUEST=GetMap&SRS=EPSG%3A2056&HEIGHT=280&WIDTH=493&VERSION=1.1.1&BBOX=2624368.91756%2C1262754.41874%2C2624511.81044%2C1263006.01226)
[PLR-WMS](https://geoview.bl.ch/main/oereb/mapservproxy?LAYERS=LandUsePlans&STYLES=default&SERVICE=WMS&FORMAT=image%2Fpng&REQUEST=GetMap&SRS=EPSG%3A2056&HEIGHT=280&WIDTH=493&VERSION=1.1.1&BBOX=2624368.91756%2C1262754.41874%2C2624511.81044%2C1263006.01226)

Both are similarly distorted. I suppose the bug lies somewhere in lib\records\view_service.py (get_bbox())

**Comment by sbuettler** [comment]
I can confirm this problem. We see the same distortion effect on our test-server. But according to our analyses, we noticed that the bbox is always calculated bigger than represented in the PDF, independent to the parcel extends. This problem leads to more elements in the "otherlegend" than visible in the WMS image.

This problem should be corrected as soon as possible. It has a quite hard impact of the main result demanded by the CH. I suggest (if it's still possible) to integrated this in the next and already offered bugfixing session. This would require a re offer of C2C.

The following example shows an extract of Ascona:

**Landregister plan in the PDF:**
![image](https://user-images.githubusercontent.com/29145003/49502022-7e14fe80-f874-11e8-842f-7fd956319e72.png)

**Landregistre plan WMS (bigger extends indicated with red lines):**
![image](https://user-images.githubusercontent.com/29145003/49502444-65591880-f875-11e8-8cc8-b5a4654f1754.png)

**Land-use-plans Topic in the PDF:**
![image](https://user-images.githubusercontent.com/29145003/49502595-abae7780-f875-11e8-8c80-cd5f200f5abd.png)

**Corresponding legend in the PDF (missing element in the map indicated in red):**
![image](https://user-images.githubusercontent.com/29145003/49502726-0051f280-f876-11e8-8833-ecae4e64e8f4.png)

**Land-use-plans Topic WMS:**
![image](https://user-images.githubusercontent.com/29145003/49502916-70607880-f876-11e8-927e-beeac35cd3fe.png)

Red point in the upper left corner: The red point is not a restriction, therefor it doesn't appear in the "otherlegend". We still work with test data :-(

**Comment by vvmruder** [comment]
Thanks for announcing this bug. I will have a look at this.

**Comment by ger-benjamin** [comment]
I'm currently on it. The calculation looks wrong

**Comment by jwkaltz** [comment]
Solved in #760
