### ISSUE TITLE
make print_proxy python3 compatible

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#719]
Currently, the print_proxy (for MapFish Print) is not fully python3 compatible.

Known issues so far:
This line https://github.com/camptocamp/pyramid_oereb/blob/a23e65e264b72a13ed159edd34aa732832ac4cdb/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L236 will generate a runtime error "dictionary changed size during iteration" when run in python3

(originally reported by Eva / Aargau)

**Comment by jwkaltz** [comment]
@pfirpfel FYI

**Comment by voisardf** [comment]
Has this not be fixed by issue https://github.com/camptocamp/pyramid_oereb/issues/695?

**Comment by jwkaltz** [comment]
Indeed, thanks @voisardf I was looking at the released version of the code, not the master branch!
