### ISSUE TITLE
are you using generateDS at all?

### ISSUE THREAD

**Issue by rvalyi** [camptocamp/pyramid_oereb#726]
Hello C2C team. It happens I will soon publish a generateDS plugin for the Odoo ERP (that you implement at C2C too), it is able to generate Odoo business objects from XSD schemas (may be C2C will be interested, so just telling). By doing a random Google of generateDS usage I found your project, because it is a dependency in your requirements.txt https://github.com/camptocamp/pyramid_oereb/blob/master/requirements.txt#L18
However I'm curious, it looks like you are using it nowhere, so is it a mistake, a left over or am I missing something?

cc @jgrandguillaume

**Comment by jwkaltz** [comment]
Hi @rvalyi , I think we are not using this, I will create a PR to remove it.

It looks like it was introduced here, but I don't know why: https://github.com/camptocamp/pyramid_oereb/blame/0a6a3ae897c88060faec3975425165a9be1d114a/setup.py#L34

**Comment by pfirpfel** [comment]
dependency removed
